export const ActionTypes = {
    SIGNIN_USER: "SIGNIN_USER",
    SIGNOUT_USER: "SIGNOUT_USER",
    THEME_DARK: "THEME_DARK",
    THEME_LIGTH: "THEME_LIGTH",
    SET_POST:"SET_POST",
    SET_COMENT_POST:"SET_COMENT_POST"
};
